debug: false
spring:
  redis:
    host: localhost
    port: 6379
    timeout: 3000
    client-name: atpco_tax_complex
#    cluster:
#      nodes:
#        - redis://10.100.45.9:10048
#        - redis://10.100.45.26:10304
#        - redis://10.100.45.15:10299
#        - redis://10.100.45.42:11251
#        - redis://10.100.45.10:10881
#        - redis://10.100.45.14:10012
#      max-redirects: 1
logging:
  level:
    root: info
    org.reddison: info
