logging:
  level:
    root: info

hbase:
  enable: true
  table-name: james
  column-family: f
  token: jw
  zookeeper: locahost
  port: 2181

spring:
  main:
    allow-bean-definition-overriding: true
